theme = "gruber-darker"

[editor]
mouse = false
line-number = "relative"
auto-save = true
auto-pairs = true
rulers = [132]
true-color = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "file-modification-indicator", "read-only-indicator","total-line-numbers", "version-control",]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
tab = ":buffer-next"
S-tab = ":buffer-previous"
S-b = ":echo %sh{git blame --date=short -L %{cursor_line},+1 %{buffer_name} | cut -d' ' -f1-4 | sed 's/$/)/g'}"

D = ["kill_to_line_end"]

[keys.normal.space]
q = ":buffer-close"

[keys.normal.space.t]
C-l = ":run-shell-command zellij run -d down -- task --list-all"
C-d = ":run-shell-command zellij run -d down -- task dev"
C-t = ":run-shell-command zellij run -d down -- task test"

[editor.lsp]
display-progress-messages = true

[editor.inline-diagnostics]
cursor-line = "hint"



